[
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 315,
    "single_price_ls": 315,
    "sharing_price_hs": 315,
    "single_price_hs": 315,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Mountainview Double Room - 2 Beds - BB",
    "sharing_price_ls": 1125,
    "single_price_ls": 1350,
    "sharing_price_hs": 1350,
    "single_price_hs": 1575,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "River View Double Room - 2 Beds - BB",
    "sharing_price_ls": 1350,
    "single_price_ls": 1575,
    "sharing_price_hs": 1650,
    "single_price_hs": 1875,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Family Chalet - 4 Bed - Min 2 - Bed Only",
    "sharing_price_ls": 1500,
    "single_price_ls": "",
    "sharing_price_hs": 1800,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 315,
    "single_price_ls": 315,
    "sharing_price_hs": 315,
    "single_price_hs": 315,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Mountain View Double Room - 2 Beds - BB",
    "sharing_price_ls": 1125,
    "single_price_ls": 1350,
    "sharing_price_hs": 1350,
    "single_price_hs": 1575,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "River View Double Room - 2 Beds - BB",
    "sharing_price_ls": 1350,
    "single_price_ls": 1575,
    "sharing_price_hs": 1650,
    "single_price_hs": 1875,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Ai-Ais Hot Springs",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Family Chalet - 4 Bed - Min 2 - Bed Only",
    "sharing_price_ls": 1500,
    "single_price_ls": "",
    "sharing_price_hs": 1800,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Orangeriver",
    "national_park": "Not in a park",
    "camp_name": "Boplass Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 86,
    "single_price_ls": 86,
    "sharing_price_hs": 86,
    "single_price_hs": 86,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Orangeriver",
    "national_park": "Not in a park",
    "camp_name": "Boplass Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 86,
    "single_price_ls": 86,
    "sharing_price_hs": 86,
    "single_price_hs": 86,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Dolomite Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 2161,
    "single_price_ls": 2399,
    "sharing_price_hs": 3016,
    "single_price_hs": 3254,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Dolomite Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Deluxe Chalet - 2 Beds - BB",
    "sharing_price_ls": 2447,
    "single_price_ls": 2685,
    "sharing_price_hs": 3598,
    "single_price_hs": 3836,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Dolomite Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 2161,
    "single_price_ls": 2399,
    "sharing_price_hs": 3016,
    "single_price_hs": 3254,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Dolomite Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Deluxe Chalet - 2 Beds - BB",
    "sharing_price_ls": 2447,
    "single_price_ls": 2685,
    "sharing_price_hs": 3598,
    "single_price_hs": 3836,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 161,
    "single_price_ls": 161,
    "sharing_price_hs": 161,
    "single_price_hs": 161,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 910,
    "single_price_ls": 910,
    "sharing_price_hs": 910,
    "single_price_hs": 910,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Baron's Room - BB",
    "sharing_price_ls": 1070,
    "single_price_ls": 1070,
    "sharing_price_hs": 1070,
    "single_price_hs": 1070,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 161,
    "single_price_ls": 161,
    "sharing_price_hs": 161,
    "single_price_hs": 161,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 910,
    "single_price_ls": 910,
    "sharing_price_hs": 910,
    "single_price_hs": 910,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Maltahohe",
    "national_park": "Not in a park",
    "camp_name": "Duwisib Castle",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Baron's Room - BB",
    "sharing_price_ls": 1070,
    "single_price_ls": 1070,
    "sharing_price_hs": 1070,
    "single_price_hs": 1070,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 200,
    "single_price_ls": 200,
    "sharing_price_hs": 200,
    "single_price_hs": 200,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Premier Chalet - BB",
    "sharing_price_ls": 2200,
    "single_price_ls": 2350,
    "sharing_price_hs": 2200,
    "single_price_hs": 2350,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1100,
    "single_price_ls": 1250,
    "sharing_price_hs": 1100,
    "single_price_hs": 1250,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 1650,
    "single_price_ls": "",
    "sharing_price_hs": 1650,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Premier Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 2200,
    "single_price_ls": "",
    "sharing_price_hs": 2200,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Self Catering Bush Chalet - 4 Beds - Min2 - Bed Only",
    "sharing_price_ls": 970,
    "single_price_ls": "",
    "sharing_price_hs": 970,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Self Catering Bush Chalet - 6 Beds - Min 3 - Bed Only",
    "sharing_price_ls": 970,
    "single_price_ls": "",
    "sharing_price_hs": 970,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 200,
    "single_price_ls": 200,
    "sharing_price_hs": 200,
    "single_price_hs": 200,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Premier Chalet - BB",
    "sharing_price_ls": 2200,
    "single_price_ls": 2350,
    "sharing_price_hs": 2200,
    "single_price_hs": 2350,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1100,
    "single_price_ls": 1250,
    "sharing_price_hs": 1100,
    "single_price_hs": 1250,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 1650,
    "single_price_ls": "",
    "sharing_price_hs": 1650,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Premier Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 2200,
    "single_price_ls": "",
    "sharing_price_hs": 2200,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Self Catering Bush Chalet - 4 Beds - Min2 - Bed Only",
    "sharing_price_ls": 970,
    "single_price_ls": "",
    "sharing_price_hs": 970,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Okahandja",
    "national_park": "Not in a park",
    "camp_name": "Gross Barmen Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Self Catering Bush Chalet - 6 Beds - Min 3 - Bed Only",
    "sharing_price_ls": 970,
    "single_price_ls": "",
    "sharing_price_hs": 970,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 1069,
    "single_price_ls": 1248,
    "sharing_price_hs": 1425,
    "single_price_hs": 1604,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 4 Bed - Min 3 - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": "",
    "sharing_price_hs": 1604,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": 1366,
    "sharing_price_hs": 1900,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - Disabled Access - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": 1366,
    "sharing_price_hs": 1900,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 3 - BB",
    "sharing_price_ls": 1829,
    "single_price_ls": "",
    "sharing_price_hs": 1900,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Honey Moon Suite - Double Bed - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 2138,
    "single_price_hs": 2317,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 1069,
    "single_price_ls": 1248,
    "sharing_price_hs": 1425,
    "single_price_hs": 1604,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 4 Bed - Min 3 - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": "",
    "sharing_price_hs": 1604,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": 1366,
    "sharing_price_hs": 1900,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - Disabled Access - BB",
    "sharing_price_ls": 1188,
    "single_price_ls": 1366,
    "sharing_price_hs": 1900,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 3 - BB",
    "sharing_price_ls": 1829,
    "single_price_ls": "",
    "sharing_price_hs": 1900,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Halali Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Honey Moon Suite - Double Bed - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 2138,
    "single_price_hs": 2317,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 177,
    "single_price_ls": 177,
    "sharing_price_hs": 177,
    "single_price_hs": 177,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "VIP Chalets - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 942,
    "single_price_ls": "",
    "sharing_price_hs": 942,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 706,
    "single_price_ls": "",
    "sharing_price_hs": 706,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 589,
    "single_price_ls": 749,
    "sharing_price_hs": 942,
    "single_price_hs": 1102,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Dormitory - 10 Beds - Min 5 - Bed only",
    "sharing_price_ls": 300,
    "single_price_ls": "",
    "sharing_price_hs": 300,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 177,
    "single_price_ls": 177,
    "sharing_price_hs": 177,
    "single_price_hs": 177,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "VIP Chalets - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 942,
    "single_price_ls": "",
    "sharing_price_hs": 942,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 706,
    "single_price_ls": "",
    "sharing_price_hs": 706,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 589,
    "single_price_ls": 749,
    "sharing_price_hs": 942,
    "single_price_hs": 1102,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Keetmanshoop",
    "national_park": "Not in a park",
    "camp_name": "Hardap Resort",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Dormitory - 10 Beds - Min 5 - Bed only",
    "sharing_price_ls": 300,
    "single_price_ls": "",
    "sharing_price_hs": 300,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Hobas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 401,
    "single_price_ls": 401,
    "sharing_price_hs": 401,
    "single_price_hs": 401,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Hobas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1557,
    "single_price_ls": 1766,
    "sharing_price_hs": 1926,
    "single_price_hs": 1926,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Hobas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 401,
    "single_price_ls": 401,
    "sharing_price_hs": 401,
    "single_price_hs": 401,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Fish River Canyon",
    "national_park": "Richtersveld Transfrontier Park",
    "camp_name": "Hobas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1557,
    "single_price_ls": 1766,
    "sharing_price_hs": 1926,
    "single_price_hs": 1926,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Jakkalsputz Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": "Jakkalsputz is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Jakkalsputz Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": "Jakkalsputz is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 268,
    "single_price_ls": 268,
    "sharing_price_hs": 268,
    "single_price_hs": 268,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet A - 2 Beds - BB",
    "sharing_price_ls": 503,
    "single_price_ls": 663,
    "sharing_price_hs": 696,
    "single_price_hs": 856,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet B - 2 Beds - BB",
    "sharing_price_ls": 599,
    "single_price_ls": 760,
    "sharing_price_hs": 760,
    "single_price_hs": 920,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds -BB",
    "sharing_price_ls": 696,
    "single_price_ls": "",
    "sharing_price_hs": 856,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 268,
    "single_price_ls": 268,
    "sharing_price_hs": 268,
    "single_price_hs": 268,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet A - 2 Beds - BB",
    "sharing_price_ls": 503,
    "single_price_ls": 663,
    "sharing_price_hs": 696,
    "single_price_hs": 856,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet B - 2 Beds - BB",
    "sharing_price_ls": 599,
    "single_price_ls": 760,
    "sharing_price_hs": 760,
    "single_price_hs": 920,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Brandberg Damaraland",
    "national_park": "Not in a park",
    "camp_name": "Khorixas Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds -BB",
    "sharing_price_ls": 696,
    "single_price_ls": "",
    "sharing_price_hs": 856,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108 Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Fisherman Chalet - Max 2 - Bed Only",
    "sharing_price_ls": 400,
    "single_price_ls": 400,
    "sharing_price_hs": 400,
    "single_price_hs": 400,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 250,
    "single_price_ls": 250,
    "sharing_price_hs": 250,
    "single_price_hs": 250,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Fisherman Chalet - Max 2 - Bed Only",
    "sharing_price_ls": 400,
    "single_price_ls": 400,
    "sharing_price_hs": 400,
    "single_price_hs": 400,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 108Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 250,
    "single_price_ls": 250,
    "sharing_price_hs": 250,
    "single_price_hs": 250,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 250,
    "single_price_ls": 250,
    "sharing_price_hs": 250,
    "single_price_hs": 250,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Fisherman Chalet - Max 2 - Bed Only",
    "sharing_price_ls": 400,
    "single_price_ls": 400,
    "sharing_price_hs": 400,
    "single_price_hs": 400,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 150,
    "single_price_ls": 150,
    "sharing_price_hs": 150,
    "single_price_hs": 150,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 250,
    "single_price_ls": 250,
    "sharing_price_hs": 250,
    "single_price_hs": 250,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Mile 72 Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Fisherman Chalet - Max 2 - Bed Only",
    "sharing_price_ls": 400,
    "single_price_ls": 400,
    "sharing_price_hs": 400,
    "single_price_hs": 400,
    "warning_messages": "Mile 72 is only open in December and January"
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1425,
    "sharing_price_hs": 1782,
    "single_price_hs": 1960,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1663,
    "single_price_ls": 1663,
    "sharing_price_hs": 2079,
    "single_price_hs": 2257,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1425,
    "sharing_price_hs": 1782,
    "single_price_hs": 1960,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Namutoni Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1663,
    "single_price_ls": 1663,
    "sharing_price_hs": 2079,
    "single_price_hs": 2257,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Naukluft Mountains",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Naukluft Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 375,
    "single_price_ls": 375,
    "sharing_price_hs": 375,
    "single_price_hs": 375,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Naukluft Mountains",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Naukluft Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1198,
    "single_price_ls": 1423,
    "sharing_price_hs": 1648,
    "single_price_hs": 1873,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Naukluft Mountains",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Naukluft Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 375,
    "single_price_ls": 375,
    "sharing_price_hs": 375,
    "single_price_hs": 375,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Naukluft Mountains",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Naukluft Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1198,
    "single_price_ls": 1423,
    "sharing_price_hs": 1648,
    "single_price_hs": 1873,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms A - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1782,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms B - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1900,
    "single_price_hs": 2198,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1663,
    "single_price_ls": 1841,
    "sharing_price_hs": 2019,
    "single_price_hs": 2317,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - Disabled Access - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1782,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 3 - BB",
    "sharing_price_ls": 1604,
    "single_price_ls": "",
    "sharing_price_hs": 2138,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Waterhole Chalet - 2 Beds - BB",
    "sharing_price_ls": 1782,
    "single_price_ls": 1960,
    "sharing_price_hs": 2613,
    "single_price_hs": 2910,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Premier Waterhole Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 2969,
    "single_price_ls": "",
    "sharing_price_hs": 4454,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 356,
    "single_price_ls": 356,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms A - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1782,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms B - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1900,
    "single_price_hs": 2198,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1663,
    "single_price_ls": 1841,
    "sharing_price_hs": 2019,
    "single_price_hs": 2317,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - Disabled Access - BB",
    "sharing_price_ls": 1425,
    "single_price_ls": 1604,
    "sharing_price_hs": 1782,
    "single_price_hs": 2079,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 3 - BB",
    "sharing_price_ls": 1604,
    "single_price_ls": "",
    "sharing_price_hs": 2138,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Waterhole Chalet - 2 Beds - BB",
    "sharing_price_ls": 1782,
    "single_price_ls": 1960,
    "sharing_price_hs": 2613,
    "single_price_hs": 2910,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Okaukuejo Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Premier Waterhole Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 2969,
    "single_price_ls": "",
    "sharing_price_hs": 4454,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Olifantsrus Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 416,
    "single_price_ls": 416,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Olifantsrus Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 416,
    "single_price_ls": 416,
    "sharing_price_hs": 416,
    "single_price_hs": 416,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Onkoshi Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Onkoshi Chalet - 2 Beds - BB",
    "sharing_price_ls": 2161,
    "single_price_ls": 2399,
    "sharing_price_hs": 3016,
    "single_price_hs": 3254,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Onkoshi Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Onkoshi Honeymoon Suite - King-size Bed - BB",
    "sharing_price_ls": 2447,
    "single_price_ls": 2685,
    "sharing_price_hs": 3598,
    "single_price_hs": 3836,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Onkoshi Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Onkoshi Chalet - 2 Beds - BB",
    "sharing_price_ls": 2161,
    "single_price_ls": 2399,
    "sharing_price_hs": 3016,
    "single_price_hs": 3254,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Etosha",
    "national_park": "Etosha National Park",
    "camp_name": "Onkoshi Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Onkoshi Honeymoon Suite - King-size Bed - BB",
    "sharing_price_ls": 2447,
    "single_price_ls": 2685,
    "sharing_price_hs": 3598,
    "single_price_hs": 3836,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 140,
    "single_price_ls": 140,
    "sharing_price_hs": 140,
    "single_price_hs": 140,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 140,
    "single_price_ls": 140,
    "sharing_price_hs": 140,
    "single_price_hs": 140,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "River Cabins - 2 Beds - BB",
    "sharing_price_ls": 1250,
    "single_price_ls": 1450,
    "sharing_price_hs": 1570,
    "single_price_hs": 1770,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "River Chalets - 2 Beds - BB",
    "sharing_price_ls": 1130,
    "single_price_ls": 1330,
    "sharing_price_hs": 1400,
    "single_price_hs": 1600,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family House - 6 Beds - Min 3 - BB",
    "sharing_price_ls": 1250,
    "single_price_ls": "",
    "sharing_price_hs": 1570,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Luxury River Cabins",
    "sharing_price_ls": 1500,
    "single_price_ls": 1700,
    "sharing_price_hs": 1800,
    "single_price_hs": 2000,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 140,
    "single_price_ls": 140,
    "sharing_price_hs": 140,
    "single_price_hs": 140,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Self-contained Campsite - Max 8",
    "sharing_price_ls": 140,
    "single_price_ls": 140,
    "sharing_price_hs": 140,
    "single_price_hs": 140,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "River Cabins - 2 Beds - BB",
    "sharing_price_ls": 1250,
    "single_price_ls": 1450,
    "sharing_price_hs": 1570,
    "single_price_hs": 1770,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "River Chalets - 2 Beds - BB",
    "sharing_price_ls": 1130,
    "single_price_ls": 1330,
    "sharing_price_hs": 1400,
    "single_price_hs": 1600,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family House - 6 Beds - Min 3 - BB",
    "sharing_price_ls": 1250,
    "single_price_ls": "",
    "sharing_price_hs": 1570,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Kavango River",
    "national_park": "Not in a park",
    "camp_name": "Popa Falls Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Luxury River Cabins",
    "sharing_price_ls": 1500,
    "single_price_ls": 1700,
    "sharing_price_hs": 1800,
    "single_price_hs": 2000,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sesriem Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 490,
    "single_price_ls": 490,
    "sharing_price_hs": 490,
    "single_price_hs": 490,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sesriem Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 490,
    "single_price_ls": 490,
    "sharing_price_hs": 490,
    "single_price_hs": 490,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Shark Island Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 268,
    "single_price_ls": 268,
    "sharing_price_hs": 268,
    "single_price_hs": 268,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Shark Island Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Lighthouse - Min 2 - Bed Only",
    "sharing_price_ls": 385,
    "single_price_ls": 385,
    "sharing_price_hs": 385,
    "single_price_hs": 385,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Shark Island Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 268,
    "single_price_ls": 268,
    "sharing_price_hs": 268,
    "single_price_hs": 268,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Shark Island Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Lighthouse - Min 2 - Bed Only",
    "sharing_price_ls": 385,
    "single_price_ls": 385,
    "sharing_price_hs": 385,
    "single_price_hs": 385,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sossus Dune Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Dune Chalet - 2 Beds - BB",
    "sharing_price_ls": 2800,
    "single_price_ls": 3080,
    "sharing_price_hs": 5040,
    "single_price_hs": 5320,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sossus Dune Lodge",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Honeymoon Suite - Double Bed - BB",
    "sharing_price_ls": 3220,
    "single_price_ls": 3500,
    "sharing_price_hs": 5586,
    "single_price_hs": 5866,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sossus Dune Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Dune Chalet - 2 Beds - BB",
    "sharing_price_ls": 2800,
    "single_price_ls": 3080,
    "sharing_price_hs": 5040,
    "single_price_hs": 5320,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Sossusvlei",
    "national_park": "Namib-Naukluft Park",
    "camp_name": "Sossus Dune Lodge",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Honeymoon Suite - Double Bed - BB",
    "sharing_price_ls": 3220,
    "single_price_ls": 3500,
    "sharing_price_hs": 5586,
    "single_price_hs": 5866,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms - DBB",
    "sharing_price_ls": 1424,
    "single_price_ls": 1601,
    "sharing_price_hs": 1083,
    "single_price_hs": 1259,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Beach Chalet - 10 Bed - min 5 - Bed Only",
    "sharing_price_ls": 1271,
    "single_price_ls": "",
    "sharing_price_hs": 789,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Beach Chalet - 8 Bed - min 4 - Bed Only",
    "sharing_price_ls": 1271,
    "single_price_ls": "",
    "sharing_price_hs": 789,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms - DBB",
    "sharing_price_ls": 1424,
    "single_price_ls": 1601,
    "sharing_price_hs": 1083,
    "single_price_hs": 1259,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Beach Chalet - 10 Bed - min 5 - Bed Only",
    "sharing_price_ls": 1271,
    "single_price_ls": "",
    "sharing_price_hs": 789,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Terrace Bay Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Beach Chalet - 8 Bed - min 4 - Bed Only",
    "sharing_price_ls": 1271,
    "single_price_ls": "",
    "sharing_price_hs": 789,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Torra Bay Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 246,
    "single_price_ls": 246,
    "sharing_price_hs": 246,
    "single_price_hs": 246,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Skeleton Coast",
    "national_park": "Skeleton Coast National Park",
    "camp_name": "Torra Bay Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 246,
    "single_price_ls": 246,
    "sharing_price_hs": 246,
    "single_price_hs": 246,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 350,
    "single_price_ls": 350,
    "sharing_price_hs": 350,
    "single_price_hs": 350,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 910,
    "single_price_ls": 1120,
    "sharing_price_hs": 1043,
    "single_price_hs": 1260,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1106,
    "single_price_ls": 1316,
    "sharing_price_hs": 1274,
    "single_price_hs": 1484,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Bush Chalet - 4 Bed - Min 2 - BB",
    "sharing_price_ls": 1106,
    "single_price_ls": "",
    "sharing_price_hs": 1246,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 1246,
    "single_price_ls": "",
    "sharing_price_hs": 1442,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2021-11-01",
    "low_season_end": "2022-06-30",
    "high_season_start": "2022-07-01",
    "high_season_end": "2022-10-31",
    "accommodation_type": "Premier Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1344,
    "single_price_ls": 1554,
    "sharing_price_hs": 1498,
    "single_price_hs": 1708,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Campsite - Max 8",
    "sharing_price_ls": 350,
    "single_price_ls": 350,
    "sharing_price_hs": 350,
    "single_price_hs": 350,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Double Rooms - BB",
    "sharing_price_ls": 910,
    "single_price_ls": 1120,
    "sharing_price_hs": 1043,
    "single_price_hs": 1260,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1106,
    "single_price_ls": 1316,
    "sharing_price_hs": 1274,
    "single_price_hs": 1484,
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Bush Chalet - 4 Bed - Min 2 - BB",
    "sharing_price_ls": 1106,
    "single_price_ls": "",
    "sharing_price_hs": 1246,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Family Chalet - 4 Beds - Min 2 - BB",
    "sharing_price_ls": 1246,
    "single_price_ls": "",
    "sharing_price_hs": 1442,
    "single_price_hs": "",
    "warning_messages": ""
  },
  {
    "supplier_name": "Namibia Wildlife Resorts",
    "area": "Waterberg",
    "national_park": "Waterberg Plateau Park",
    "camp_name": "Waterberg Camp",
    "low_season_start": "2020-11-01",
    "low_season_end": "2021-06-30",
    "high_season_start": "2021-07-01",
    "high_season_end": "2021-10-31",
    "accommodation_type": "Premier Bush Chalet - 2 Beds - BB",
    "sharing_price_ls": 1344,
    "single_price_ls": 1554,
    "sharing_price_hs": 1498,
    "single_price_hs": 1708,
    "warning_messages": ""
  }
]